//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GradeBySemester
    {
        public int StudentID { get; set; }
        public int SemesterID { get; set; }
        public int GradeID { get; set; }
        public decimal AverageScore { get; set; }
    
        public virtual Grade Grade { get; set; }
        public virtual Student Student { get; set; }
    }
}
