//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grade
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Grade()
        {
            this.GradeBySemesters = new HashSet<GradeBySemester>();
        }
    
        public int GradeID { get; set; }
        public int StudentID { get; set; }
        public int CourseID { get; set; }
        public System.DateTime ExamDate { get; set; }
        public int SemesterID { get; set; }
        public decimal ScoreScale10 { get; set; }
        public Nullable<decimal> ScoreScale4 { get; set; }
        public string LetterGrade { get; set; }
    
        public virtual Cours Cours { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GradeBySemester> GradeBySemesters { get; set; }
        public virtual Student Student { get; set; }
        public virtual Semester Semester { get; set; }
    }
}
